using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorDemo.Generator;

[Generator]
public class SampleGenerator : IIncrementalGenerator
{
    private const string HelloWorld =
        """
        //加上此行以防止编译器进行不必要的代码分析，避免出现警告
        //<auto-generated>
        using System;
        namespace SourceGeneratorDemo.Generator;

        public class HelloWorld
        {
            public static void SayHello()
            {
                Console.WriteLine("Hello, World!");
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //在编译时生成源代码
        context.RegisterPostInitializationOutput(ctx => 
            ctx.AddSource("HelloWorld.g.cs",SourceText.From(HelloWorld, Encoding.UTF8)));
    }
}